---

- name: Configuring service
  service: >
    name=fail2ban
    state={{ fail2ban_service_state }}
    enabled={{ fail2ban_service_enabled }}
  tags:
    - system
    - networking
    - fail2ban
    - config
